wtf:
  colors:
    background: #00000000
    border:
      focusable: blue
      focused: lightblue
      normal: blue
  grid:
    columns: [40]
    rows: [10, 7, 8, 9, 18, 28]
  refreshInterval: 1
  term: "xterm-256color"
  mods:
    ipinfo:
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
      colors:
        name: blue
        value: lightblue
    git:
      enabled: true
      position:
        top: 5
        left: 0
        height: 1
        width: 1
      refreshInterval: 2
      commitCount: 4
      repositories:
        - "/home/eyoungberg/Projects/mapc/myschoolcommute2"
        - "/home/eyoungberg/Projects/mapc/digitalhub"
    github:
      enabled: true
      position:
        top: 4
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      repositories:
        digitalhub: "MAPC"
        myschoolcommute2: "MAPC"
        prql: "PrQL"
      username: "ericyoungberg"
    weather:
      enabled: true
      refreshInterval: 900
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      tempUnit: "F"
      language: "EN"
      cityids:
        - 4930956
        - 4887398
      colors:
        current: blue
    clocks:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      colors:
        rows:
          even: "blue"
          odd: "white"
      locations:
        Boston: "America/New_York"
        Beijing: "Asia/Hong_Kong"
        Chicago: "America/Chicago"
        Paris: "Europe/Paris"
        Vancouver: "America/Vancouver"
      refreshInterval: 15
      sort: "chronological"
    security:
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
